from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class CopilotQueryRequest(BaseModel):
    """Dispatcher inquiry submitted to the AI Operations Copilot."""
    query_text: str = Field(..., description="Natural language prompt or spoken voice query from dispatcher")
    tenant_slug: Optional[str] = Field(None, description="Optional contractor tenant slug identifier")


class CopilotSuggestedAction(BaseModel):
    """Clickable deep-link action button generated by the copilot for immediate execution."""
    label: str = Field(..., description="Button label text (e.g. 'View Leaderboard', 'Open Live Map')")
    url: str = Field(..., description="Relative or absolute application URL")
    action_type: str = Field("NAVIGATE", description="Action execution type: NAVIGATE, MODAL, or TRIGGER")
    variant: str = Field("primary", description="Button visual style: primary, warning, or emerald")


class CopilotQueryResponse(BaseModel):
    """Structured synthesized operational response with action recommendations."""
    answer_text: str = Field(..., description="Clear, professional operational response summary in markdown")
    intent: str = Field(
        ...,
        description="Detected intent category: METRICS, TECHNICIAN_KPI, EMERGENCY_SUMMARY, WEATHER_RISK, or GENERAL",
    )
    suggested_actions: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Contextual action buttons to view reports or resolve bottlenecks",
    )
    data_payload: Optional[Dict[str, Any]] = Field(
        None,
        description="Structured telemetry metrics supporting the answer",
    )
