from typing import List, Optional
from pydantic import BaseModel, Field


class ToolItem(BaseModel):
    """High-value tool or diagnostic instrument assigned to a service van."""
    tool_name: str = Field(..., description="Exact commercial tool or instrument name")
    brand: str = Field(..., description="Manufacturer brand e.g. Milwaukee, RIDGID, Fieldpiece, DeWalt, Fluke")
    category: str = Field(..., description="Asset classification e.g. Diagnostic Meter, Press Tool, Vacuum Pump")
    estimated_value: float = Field(..., description="Replacement replacement value in USD")


class TruckToolRegistry(BaseModel):
    """Registry profile of a service van and its mandatory tool inventory."""
    truck_id: str = Field(..., description="Unique vehicle asset ID e.g. VAN-01")
    driver_name: str = Field(..., description="Technician or driver assigned to the vehicle")
    trade_type: str = Field(..., description="Primary trade specialization e.g. HVAC, Plumbing, Electrical, Roofing")
    required_tools: List[ToolItem] = Field(default_factory=list, description="Mandatory tool inventory list")
    last_audit_date: Optional[str] = Field(None, description="ISO timestamp of most recent asset audit")
    compliance_status: str = Field("ACTIVE", description="Current tool compliance status: ACTIVE, WARNING, AUDIT_REQUIRED")


class ToolAuditReport(BaseModel):
    """Audit report generated by Gemini Multimodal Vision inspecting van tool shelving/racks."""
    truck_id: str = Field(..., description="Vehicle asset identifier")
    audit_timestamp: str = Field(..., description="ISO timestamp of audit execution")
    verified_tools: List[ToolItem] = Field(default_factory=list, description="Tools positively detected in photo")
    missing_tools: List[ToolItem] = Field(default_factory=list, description="Mandatory tools absent from shelving")
    audit_score: float = Field(..., description="Asset compliance percentage 0.0 to 100.0")
    replacement_cost_at_risk: float = Field(..., description="Total estimated value of missing tools in USD")
    status: str = Field(..., description="Audit outcome status: PASS or MISSING_ASSETS")
    audit_notes: Optional[str] = Field(None, description="Detailed observations or recommendations from auditor")


class ToolAuditResponse(BaseModel):
    """API response wrapper for completed tool audit."""
    status: str = Field(..., description="Audit submission status: SUCCESS or FAILED")
    report: ToolAuditReport = Field(..., description="Full tool audit report")
    message: str = Field(..., description="Human-readable summary message")
