from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class EquipmentDiagnosticReport(BaseModel):
    """Structured multimodal vision diagnostic report generated by Gemini."""
    equipment_type: str = Field(
        description="Detected trade equipment category (e.g. HVAC Condenser, Water Heater, Electrical Panel, Plumbing Pipe, Roofing, Furnace)"
    )
    brand_manufacturer: Optional[str] = Field(
        default=None,
        description="Identified manufacturer brand (e.g. Carrier, Rheem, Square D, Trane, Lennox, Bradford White)",
    )
    model_number: Optional[str] = Field(
        default=None,
        description="Extracted model number from equipment data plate or label",
    )
    serial_number: Optional[str] = Field(
        default=None,
        description="Extracted serial number from equipment data plate or label",
    )
    detected_materials: List[str] = Field(
        default_factory=list,
        description="Visible construction or plumbing materials (e.g. Copper, PEX, PVC, Architectural Shingles, Romex Wire)",
    )
    damage_assessment: str = Field(
        description="Concise description of visible issue, wear, failure, corrosion, scorch marks, or leak",
    )
    recommended_parts_tools: List[str] = Field(
        default_factory=list,
        description="Suggested truck stock parts, fittings, and diagnostic tools for technician",
    )
    confidence_score: float = Field(
        default=0.85,
        ge=0.0,
        le=1.0,
        description="Confidence score for the visual diagnosis (0.0 to 1.0)",
    )


class DiagnosticSubmissionResponse(BaseModel):
    """API response model after diagnostic image upload and analysis."""
    success: bool = True
    action_id: str
    tenant_slug: str
    report: EquipmentDiagnosticReport
    sms_alert_sent: bool = False
    crm_synced: bool = False
